routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Item\ItemController;
use App\Http\Controllers\Item\CategoryController;
use App\Http\Controllers\Item\TagController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\ReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

Route::get('/', [ItemController::class, 'index'])
    ->middleware('auth');

Route::get('/test', [App\Http\Controllers\TestController::class, 'index'])
    ->middleware('auth');

Route::resource('/category', CategoryController::class)
    ->middleware('auth')
    ->only(['index', 'store', 'destroy']);

Route::resource('/tag', TagController::class)
    ->middleware('auth')
    ->only(['index', 'store', 'destroy']);

Route::resource('/item', ItemController::class)
    ->middleware('auth')
    ->only(['index', 'show', 'store', 'destroy', 'update']);

Route::resource('/inventory', InventoryController::class)
    ->middleware('auth')
    ->only(['index', 'create', 'store', 'destroy', 'edit', 'update']);

Route::resource('/report', ReportController::class)
    ->middleware('auth')
    ->only(['index']);

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'category_id'];

    public function category(){
        return $this->belongsTo('App\Models\Category');
    }

    public function tags(){
        return $this->belongsToMany('App\Models\Tag', 'Item_tag');
    }

    public function RemoveAllTags(){
        $AllTags = $this->tags()->detach();
    }

}

app/Http/Controllers/Item/CategoryController.php
<?php

namespace App\Http\Controllers\Item;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCategory;
use App\Models\Category;
use App\Models\Item;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $Categories = Category::all()->where('isActive',true);

        return view('item.category')->with(['ActiveCategories'=>$Categories]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCategory $request)
    {
        //validation
        $validated = $request->validated();

        $Cat = new Category();
        $Cat->name = $validated['name'];
        $Cat->save();
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $Category = Category::findOrFail($id);
        $Category->isActive = 0;
        $Category->save();

        return redirect()->route('category.index');
    }
}

app/Http/Controllers/Item/ItemController.php
<?php

namespace App\Http\Controllers\Item;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreItem;
use App\Models\Category;
use App\Models\Item;
use App\Models\Tag;
use http\Exception;
use Illuminate\Http\Request;
use function Laravel\Prompts\error;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): \Illuminate\Contracts\View\View
    {
        $Item = Item::all()->where('isActive',true);
        $Categories = Category::all()->where('isActive',true);
        $Tags = Tag::all()->where('isActive',true);

        return view('item.item')->with([
            'ActiveItem' => $Item,
            'AllCategories' => $Categories,
            'AllTags' => $Tags,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreItem $request): \Illuminate\Http\RedirectResponse
    {
        //validation
        $validated = $request->validated();

        try {
            $Item = new Item();
            $Item->name = $validated['name'];
            $Item->category_id = $validated['category_id'];
            $Item->save();

            foreach ($request->tags as $tag){
                $Item->tags()->attach(Tag::findOrFail($tag));
            }

        } catch (\Exception $e) {
            report($e);
        }

        return redirect()->route('item.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id): \Illuminate\Http\RedirectResponse
    {
        $Item = Item::findOrFail($id);
        $Item->isActive = 0;
        $Item->save();

        return redirect()->route('item.index');
    }

    public function show(string $id)
    {
        $Item = Item::findOrFail($id);
        $Categories = Category::all()->where('isActive',true);
        $Tags = Tag::all()->where('isActive',true);

        $itemTags = $Item->Tags()->get();
        $ItemTagsIds = [];
        foreach ($itemTags as $itemTag){
            $ItemTagsIds[] = $itemTag->id;
        }

        return view('item.item-edit')->with([
            'Item' => $Item,
            'AllCategories' => $Categories,
            'AllTags' => $Tags,
            'ItemTagsIds' => $ItemTagsIds
        ]);
    }

    public function update(StoreItem $request, string $id)
    {
        //validation
        $validated = $request->validated();

        try {
            $Item = Item::findOrFail($id);
            $Item->name = $validated['name'];
            $Item->category_id = $validated['category_id'];
            $Item->save();

            $Item->RemoveAllTags();

            foreach ($request->tags as $tag){
                $Item->tags()->attach(Tag::findOrFail($tag));
            }

        } catch (\Exception $e) {
            report($e);
        }

        return redirect()->route('item.index');
    }
}

app/Http/Controllers/Item/TagController.php
<?php

namespace App\Http\Controllers\Item;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreTag;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\View\View;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): \Illuminate\Contracts\View\View
    {
        $Tag = Tag::all()->where('isActive',true);

        return view('item.Tag')->with(['ActiveTag'=>$Tag]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreTag $request): \Illuminate\Http\RedirectResponse
    {
        //validation
        $validated = $request->validated();

        $Tag = new Tag();
        $Tag->name = $validated['name'];
        $Tag->save();
        return redirect()->route('tag.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id): \Illuminate\Http\RedirectResponse
    {
        $Tag = Tag::findOrFail($id);
        $Tag->isActive = 0;
        $Tag->save();

        return redirect()->route('tag.index');
    }
}

resources/views/item/category.blade.php
@extends('layouts.master')

@section('styles')
@endsection

@section('content')
    <!-- Start::app-content -->
    <div class="main-content app-content">
        <div class="container-fluid">

            <!-- Page Header -->
            <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
                <h1 class="page-title fw-medium fs-24 mb-0">Categories</h1>
            </div>
            <!-- Page Header Close -->

            <!-- Start::row-1 -->
            <div class="row">
                <div class="col-xl-12">
                    <div class="card custom-card">
                        <div class="card-body">
                            <div class="col-md-12">
                                @include('components.error')

                                @include('components.add-category')

                                <div class="card custom-card">
                                    <div class="card-header justify-content-between">
                                        <div class="card-title">
                                            {{__('Active')}}
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table class="table text-nowrap table-striped-columns">
                                                <thead>
                                                <tr>
                                                    <th scope="col">#</th>
                                                    <th scope="col">Name</th>
                                                    <th scope="col">Item Count</th>
                                                    <th scope="col">Active</th>
                                                    <th scope="col"></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                @foreach($ActiveCategories as $Cat)
                                                <tr>
                                                    <th scope="row">{{$loop->iteration}}</th>
                                                    <td>{{$Cat->name}}</td>
                                                    <td class="text-center">{{count($Cat->items)}}</td>
                                                    <td class="text-center"><i class="bx bxs-circle text-green fs-10 rounded-circle"></i></td>
                                                    <td>
                                                        <form method="POST" action="{{route('category.destroy', $Cat->id)}}">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit" class="btn btn-sm btn-danger btn-wave">
                                                                <i class="ri-delete-bin-line align-middle me-2 d-inline-block"></i>Delete
                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                                @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="card-footer d-none border-top-0">
                        </div>
                    </div>
                </div>
            </div>
            <!--End::row-1 -->

        </div>
    </div>
    <!-- End::app-content -->

@endsection

@section('scripts')
@endsection

resources/views/item/item-edit.blade.php
@extends('layouts.master')

@section('styles')
    <link rel="stylesheet" href="{{asset('build/assets/libs/tom-select/css/tom-select.default.min.css')}}">
@endsection

@section('content')
    <!-- Start::app-content -->
    <div class="main-content app-content">
        <div class="container-fluid">

            <!-- Page Header -->
            <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
                <h1 class="page-title fw-medium fs-24 mb-0">Empty Page</h1>
            </div>
            <!-- Page Header Close -->

            <!-- Start::row-1 -->
            <div class="row">
                <div class="col-xl-12">
                    <div class="card custom-card">
                        <div class="card-body col-xl-8 m-auto">

                            <div aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <form action="{{route('item.update',$Item->id)}}" method="POST"
                                              class="row g-3 needs-validation p-5">
                                            @method('PUT')
                                            @csrf
                                            <div class="mb-3">
                                                <label for="itemName" class="col-form-label">Item Name<span class="text-danger">*</span></label>
                                                <input type="text" class="form-control" id="itemName" value="{{$Item['name']}}"
                                                       name="name" required>
                                            </div>
                                            <div class="mb-3">
                                                <div class="card custom-card">
                                                    <div class="card-header justify-content-between">
                                                        <div class="card-title">
                                                            Select Category<span class="text-danger">*</span>
                                                        </div>
                                                    </div>
                                                    <div class="card-body">
                                                        <select name="category_id" class="form-select form-select-sm mb-3" aria-label=".form-select-sm example" required>
                                                            <option selected=""></option>
                                                            @foreach($AllCategories as $Category)
                                                                <option {{ $Item->category_id == $Category->id? 'selected' : '' }}
                                                                    value="{{$Category->id}}">{{$Category->name}}</option>
                                                            @endforeach
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="mb-3">
                                                <div class="card-body">
                                                    <p class="fw-semibold mb-2">Select Tags</p>
                                                    <select class="form-control" name="tags[]" id="choices-multiple-remove-button" multiple>
                                                        @foreach($AllTags as $Tag)
                                                            <option {{in_array($Tag->id, $ItemTagsIds)? 'selected' : '' }}
                                                                value="{{$Tag->id}}">{{$Tag->name}}</option>
                                                        @endforeach

                                                    </select>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-primary">Update</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!--End::row-1 -->

        </div>
    </div>
    <!-- End::app-content -->

@endsection

@section('scripts')
    <script src="{{asset('build/assets/libs/tom-select/js/tom-select.complete.min.js')}}"></script>
    <script>
        (function () {
            "use strict";

            /* multi select with remove button */
            const multipleCancelButton = new Choices(
                '#choices-multiple-remove-button',
                {
                    allowHTML: true,
                    removeItemButton: true,
                }
            );
        })();
    </script>
@endsection

resources/views/item/item.blade.php
@extends('layouts.master')

@section('styles')

    <!-- Prism CSS -->
{{--    <link rel="stylesheet" href="{{asset('build/assets/libs/prismjs/themes/prism-coy.min.css')}}">--}}

    <!-- Tom Select Css -->
    <link rel="stylesheet" href="{{asset('build/assets/libs/tom-select/css/tom-select.default.min.css')}}">

@endsection

@section('content')
    <!-- Start::app-content -->
    <div class="main-content app-content">
        <div class="container-fluid">

            <!-- Page Header -->
            <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
                <h1 class="page-title fw-medium fs-24 mb-0">Items</h1>
            </div>
            <!-- Page Header Close -->

            <!-- Start::row-1 -->
            <div class="row">
                <div class="col-xl-12">
                    <div class="card custom-card">
                        <div class="card-body">
                            <div class="col-md-12">
                                @include('components.error')
                                <button type="button" class="btn btn-primary mb-1" data-bs-toggle="modal"
                                        data-bs-target="#AddTag" data-bs-whatever="@mdo">ADD
                                </button>

                                @include('components.add-item')

                                <div class="card custom-card">
                                    <div class="card-header justify-content-between">
                                        <div class="card-title">
                                            {{__('Active')}}
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table class="table text-nowrap table-striped-columns">
                                                <thead>
                                                <tr>
                                                    <th scope="col">#</th>
                                                    <th scope="col">Name</th>
                                                    <th scope="col">Category</th>
                                                    <th scope="col">Tags</th>
                                                    <th scope="col">Active</th>
                                                    <th scope="col"></th>
                                                    <th scope="col"></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                @foreach($ActiveItem as $Item)
                                                    <tr>
                                                        <th scope="row">{{$loop->iteration}}</th>
                                                        <td>{{$Item->name}}</td>
                                                        <td class="text-center">{{$Item->category->name}}</td>
                                                        <td class="text-center">
                                                            @foreach($Item->tags as $Tag)
                                                                <a href="javascript:void(0);" class="btn btn-primary">{{$Tag->name}}</a>
                                                            @endforeach
                                                        </td>
                                                        <td class="text-center"><i
                                                                class="bx bxs-circle text-green fs-10 rounded-circle"></i>
                                                        </td>
                                                        <td><a href="{{route('item.show',$Item->id)}}" class="btn btn-warning rounded-pill btn-wave waves-effect waves-light">EDIT</a></td>
                                                        <td>
                                                            <form method="POST"
                                                                  action="{{route('item.destroy', $Item->id)}}">
                                                                @csrf
                                                                @method('DELETE')
                                                                <button type="submit" class="btn btn-danger rounded-pill btn-wave waves-effect waves-light">DELETE</button>
                                                            </form>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="card-footer d-none border-top-0">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--End::row-1 -->

                    </div>
                </div>
                <!-- End::app-content -->

@endsection

@section('scripts')

    <!-- Prism JS -->
{{--    <script src="{{asset('build/assets/libs/prismjs/prism.js')}}"></script>--}}
{{--    @vite('resources/assets/js/prism-custom.js')--}}

    <!-- Tom Select JS -->
    <script src="{{asset('build/assets/libs/tom-select/js/tom-select.complete.min.js')}}"></script>
{{--    @vite('resources/assets/js/tom-select.js')--}}
    <script>
        (function () {
            "use strict";

            /* multi select with remove button */
            const multipleCancelButton = new Choices(
                '#choices-multiple-remove-button',
                {
                    allowHTML: true,
                    removeItemButton: true,
                }
            );
        })();
    </script>
    <!-- Internal Choices JS -->
{{--    @vite('resources/assets/js/choices.js')--}}
@endsection

resources/views/item/tag.blade.php
@extends('layouts.master')

@section('styles')
@endsection

@section('content')
    <!-- Start::app-content -->
    <div class="main-content app-content">
        <div class="container-fluid">

            <!-- Page Header -->
            <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
                <h1 class="page-title fw-medium fs-24 mb-0">Tags</h1>
            </div>
            <!-- Page Header Close -->

            <!-- Start::row-1 -->
            <div class="row">
                <div class="col-xl-12">
                    <div class="card custom-card">
                        <div class="card-body">
                            <div class="col-md-12">
                                @include('components.error')
                                <button type="button" class="btn btn-primary mb-1" data-bs-toggle="modal"
                                        data-bs-target="#AddTag" data-bs-whatever="@mdo">ADD
                                </button>

                                <div class="modal fade" id="AddTag" tabindex="-1"
                                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h6 class="modal-title" id="exampleModalLabel">New Tag</h6>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                            </div>
                                            <form action="{{route('tag.store')}}" method="POST"
                                                  class="row g-3 needs-validation">
                                                @csrf
                                                <div class="modal-body">
                                                    <div class="mb-3">
                                                        <label for="tagName" class="col-form-label">Tag Name:</label>
                                                        <input type="text" class="form-control" id="tagName"
                                                               name="name">
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                            data-bs-dismiss="modal">Close
                                                    </button>
                                                    <button type="submit" class="btn btn-primary">Submit</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="card custom-card">
                                    <div class="card-header justify-content-between">
                                        <div class="card-title">
                                            {{__('Active')}}
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table class="table text-nowrap table-striped-columns">
                                                <thead>
                                                <tr>
                                                    <th scope="col">#</th>
                                                    <th scope="col">Name</th>
                                                    <th scope="col">Item Count</th>
                                                    <th scope="col">Active</th>
                                                    <th scope="col"></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                @foreach($ActiveTag as $Tag)
                                                    <tr>
                                                        <th scope="row">{{$loop->iteration}}</th>
                                                        <td>{{$Tag->name}}</td>
                                                        <td class="text-center">{{count($Tag->Items)}}</td>
                                                        <td class="text-center"><i
                                                                class="bx bxs-circle text-green fs-10 rounded-circle"></i>
                                                        </td>
                                                        <td>
                                                            <form method="POST"
                                                                  action="{{route('tag.destroy', $Tag->id)}}">
                                                                @csrf
                                                                @method('DELETE')
                                                                <button type="submit"
                                                                        class="btn btn-sm btn-danger btn-wave">
                                                                    <i class="ri-delete-bin-line align-middle me-2 d-inline-block"></i>Delete
                                                                </button>
                                                            </form>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="card-footer d-none border-top-0">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--End::row-1 -->

                    </div>
                </div>
                <!-- End::app-content -->

@endsection

@section('scripts')
@endsection