routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Item\ItemController;
use App\Http\Controllers\Item\CategoryController;
use App\Http\Controllers\Item\TagController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\ReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

Route::get('/', [ItemController::class, 'index'])
    ->middleware('auth');

Route::get('/test', [App\Http\Controllers\TestController::class, 'index'])
    ->middleware('auth');

Route::resource('/category', CategoryController::class)
    ->middleware('auth')
    ->only(['index', 'store', 'destroy']);

Route::resource('/tag', TagController::class)
    ->middleware('auth')
    ->only(['index', 'store', 'destroy']);

Route::resource('/item', ItemController::class)
    ->middleware('auth')
    ->only(['index', 'show', 'store', 'destroy', 'update']);

Route::resource('/inventory', InventoryController::class)
    ->middleware('auth')
    ->only(['index', 'create', 'store', 'destroy', 'edit', 'update']);

Route::resource('/report', ReportController::class)
    ->middleware('auth')
    ->only(['index']);

app/Models/Inventory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    use HasFactory;

    public function inventory_type(){
        return $this->belongsTo('App\Models\Inventory_type');
    }

    public function inventory_count(){
        return $this->hasMany('App\Models\inventory_count');
    }
}

app/Models/Inventory_type.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inventory_type extends Model
{
    use HasFactory;

    public function inventory(){
        return $this->hasMany('App\Models\Inventory');
    }
}

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreInventory;
use App\Models\Category;
use App\Models\Inventory;
use App\Models\inventory_count;
use App\Models\Inventory_type;
use App\Models\Item;
use Illuminate\Http\Request;

class InventoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $Inventory = Inventory::all()
            ->where('isActive',true);

        return view('inventory.index', ['Inventories'=>$Inventory]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $allItems = Item::all()->where('isActive',true);
        $inventoryTypeId = Inventory_type::all();

        $itemsByCategory = [];

        foreach ($allItems as $item){
            $itemCategoryName = $item->category->name;
            if(!array_key_exists($itemCategoryName, $itemsByCategory)){
                $itemsByCategory[$itemCategoryName] = [];
            }
            $itemsByCategory[$itemCategoryName][] = $item;
        }


        return view('inventory.create')
            ->with([
                'ItemsByCategory' => $itemsByCategory,
                'InventoryType' => $inventoryTypeId
            ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreInventory $request)
    {
        //validation
        $validated = $request->validated();

        $inventoryObj = new Inventory();
        $inventoryObj->InventoryDate = $validated['InventoryDate'];

        $InvTypeObj = Inventory_type::findOrFail($validated['inventoryType_id']);

        $inventoryObj->inventory_type()->associate($InvTypeObj);

        foreach ($request->all() as $key=>$value){
            $InventoryCountValue = (int)$value;
            if($InventoryCountValue<=0){
                continue;
            }

            if($inventoryObj->id === null){
                $inventoryObj->save();
            }
            if(is_int($key)){
                try {
                    $Item = Item::findOrFail($key);

                    $InventoryCount = new inventory_count();
                    $InventoryCount->item_count = $InventoryCountValue;
                    $InventoryCount->item()->associate($Item);
                    $InventoryCount->inventory()->associate($inventoryObj);
                    $InventoryCount->save();
                }catch (\Exception $e) {

                    return $e->getMessage();
                }
            }
        }
        return redirect()->route('inventory.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $allItems = Item::all()->where('isActive',true);
        $inventoryTypeId = Inventory_type::all();
        $inventory = inventory::findOrFail($id);

        if(!$inventory->isActive){
            return view('inventory.index');
        }

        $invCounts = $inventory->inventory_count;

        $invCountsByItemId = [];

        foreach ($invCounts as $invCount){
            $invCountsByItemId[$invCount->item->id] = $invCount;
        }

        $itemsByCategory = [];

        foreach ($allItems as $item){
            $itemCategoryName = $item->category->name;
            if(!array_key_exists($itemCategoryName, $itemsByCategory)){
                $itemsByCategory[$itemCategoryName] = [];
            }
            $itemsByCategory[$itemCategoryName][] = $item;
        }

        return view('inventory.edit')
            ->with([
                'ItemsByCategory' => $itemsByCategory,
                'InventoryType' => $inventoryTypeId,
                'inventory' => $inventory,
                'invCountsByItemId' => $invCountsByItemId
            ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //validation

        $inventory = Inventory::findOrFail($id);
        $inventory_countObj = Inventory::findOrFail($id)->inventory_count;

        foreach ($inventory_countObj as $C){
            $C->isActive = false;
            $C->delete();
        }

        $AllSubmittedFields = $request->input();

        foreach ($AllSubmittedFields as $FieldItemid => $Field){
            try {
                if(is_int($FieldItemid)){
                    $item = Item::findOrFail($FieldItemid);
                    $Count = (int)$Field;
                    if($Count<=0){
                        continue;
                    }

                    $InventoryCount = new inventory_count();
                    $InventoryCount->item_count = $Field;
                    $InventoryCount->item()->associate($item);
                    $InventoryCount->inventory()->associate($inventory);
                    $InventoryCount->save();

                }
            } catch (\Exception $e) {
            }
        }
        return redirect()->route('inventory.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $inventory = Inventory::findOrFail($id);
        $inventory->isActive=false;
        $inventory->save();

        return redirect()->route('inventory.index');

    }
}

resources/views/inventory/create.blade.php
@extends('layouts.master')

@section('styles')
@endsection

@section('content')
    <!-- Start::app-content -->
    <div class="main-content app-content">
        <div class="container-fluid">

            <!-- Page Header -->
            <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
                <h1 class="page-title fw-medium fs-24 mb-0">Empty Page</h1>
            </div>
            <!-- Page Header Close -->

            <!-- Start::row-1 -->
            <form action="{{route('inventory.store')}}" method="POST"
                  class="row g-3 needs-validation">
                @csrf
                <div class="col-xl-12">
                    <div class="card custom-card">
                        <div class="card-body">
                            <div class="row">
                                <div class="row">
                                    <div class="col-md-3 mb-3">
                                        <div class="col-xl-12 mb-3">
                                            <label class="form-label">Date</label>
                                            <input type="date" class="form-control" name="InventoryDate" required>
                                        </div>
                                    </div>
                                    <div class="col-md-9 mb-3 mt-4">
                                        @foreach($InventoryType as $InvType)
                                            <div class="form-check form-check-md mb-3">
                                                <input class="form-check-input" type="radio" name="inventoryType_id" value="{{$InvType->id}}" required>
                                                <label class="form-check-label" for="Radio-md">
                                                    {{$InvType->type}}
                                                </label>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                @foreach($ItemsByCategory as $Category=>$Items)
                    <div class="col-xl-12">
                        <div class="card custom-card">
                            <div class="card-body">
                                <div class="row">
                                    <h4 class="page-title fw-medium fs-24 mb-5">{{$Category}}</h4>
                                    <div class="row">
                                        @foreach($Items as $Item)
                                            <div class="col-md-3 mb-3">
                                                <label class="form-label">{{$Item->name}}</label>
                                                <input type="number" name="{{$Item->id}}" class="form-control" placeholder=""
                                                       aria-label="Phone number">
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
                <div class="col-xl-12">
                    <div class="card custom-card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- End::app-content -->

@endsection

@section('scripts')
@endsection

resources/views/inventory/edit.blade.php
@extends('layouts.master')

@section('styles')
@endsection

@section('content')
    <!-- Start::app-content -->
    <div class="main-content app-content">
        <div class="container-fluid">

            <!-- Page Header -->
            <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
                <h1 class="page-title fw-medium fs-24 mb-0">Empty Page</h1>
            </div>
            <!-- Page Header Close -->

            <!-- Start::row-1 -->
            <form action="{{route('inventory.update', $inventory->id)}}" method="POST"
                  class="row g-3 needs-validation">
                @csrf
                @method('PATCH')
                <div class="col-xl-12">
                    <div class="card custom-card">
                        <div class="card-body">
                            <div class="row">
                                <div class="row">
                                    <div class="col-md-3 mb-3">
                                        <div class="col-xl-12 mb-3">
                                            <label class="form-label">Date</label>
                                            <h3>{{date('M d Y', strtotime($inventory->InventoryDate))}}</h3>
                                        </div>
                                    </div>
                                    <div class="col-md-9 mb-3 mt-4">
                                        @foreach($InventoryType as $InvType)
                                            <div class="form-check form-check-md mb-3">
                                                <input class="form-check-input" type="radio" name="inventoryType_id"
                                                       value="{{$InvType->id}}" required disabled
                                                        @if($InvType->type == $inventory->inventory_type->type)
                                                           checked="checked"
                                                        @endif
                                                >
                                                <label class="form-check-label" for="Radio-md">
                                                    {{$InvType->type}}
                                                </label>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                @foreach($ItemsByCategory as $Category=>$Items)
                    <div class="col-xl-12">
                        <div class="card custom-card">
                            <div class="card-body">
                                <div class="row">
                                    <h4 class="page-title fw-medium fs-24 mb-5">{{$Category}}</h4>
                                    <div class="row">
                                        @foreach($Items as $Item)
                                            <div class="col-md-3 mb-3">
                                                <label class="form-label">{{$Item->name}}</label>
                                                <input type="number" name="{{$Item->id}}" class="form-control"
                                                       placeholder=""
                                                       aria-label="Phone number"
                                                        @if(array_key_exists($Item->id, $invCountsByItemId))
                                                           value="{{$invCountsByItemId[$Item->id]->item_count}}"
                                                        @else
                                                            value="0"
                                                        @endif
                                                >
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
                <div class="col-xl-12">
                    <div class="card custom-card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- End::app-content -->

@endsection

@section('scripts')
@endsection

resources/views/inventory/index.blade.php
@extends('layouts.master')

@section('styles')
@endsection

@section('content')
    <!-- Start::app-content -->
    <div class="main-content app-content">
        <div class="container-fluid">

            <!-- Page Header -->
            <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
                <h1 class="page-title fw-medium fs-24 mb-0">Empty Page</h1>
            </div>
            <!-- Page Header Close -->

            <!-- Start::row-1 -->
            <div class="row">
                <div class="col-xl-12">
                    <div class="card custom-card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <a href="{{route('inventory.create')}}" type="button" class="btn btn-secondary btn-wave btn-lg mb-3"> Add </a>
                                <table class="table text-nowrap">
                                    <thead class="table-th-primary">
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Date</th>
                                        <th scope="col">Type</th>
                                        <th scope="col">Status</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($Inventories as $inventory)
                                        <tr>
                                            <th scope="row">{{$loop->iteration}}</th>
                                            <td>{{date('M d Y', strtotime($inventory->InventoryDate))}}</td>
                                            <td>{{$inventory->inventory_type->type}}</td>
                                            <td>
                                                <div class="hstack gap-2 fs-15">
                                                    <x-form.edit href="{{route('inventory.edit', $inventory->id)}}"></x-form.edit>
                                                    <x-form.delete action="{{route('inventory.destroy', $inventory)}}"></x-form.delete>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End::row-1 -->

        </div>
    </div>
    <!-- End::app-content -->

@endsection

@section('scripts')
@endsection