routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Item\ItemController;
use App\Http\Controllers\Item\CategoryController;
use App\Http\Controllers\Item\TagController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\ReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

Route::get('/', [ItemController::class, 'index'])
    ->middleware('auth');

Route::get('/test', [App\Http\Controllers\TestController::class, 'index'])
    ->middleware('auth');

Route::resource('/category', CategoryController::class)
    ->middleware('auth')
    ->only(['index', 'store', 'destroy']);

Route::resource('/tag', TagController::class)
    ->middleware('auth')
    ->only(['index', 'store', 'destroy']);

Route::resource('/item', ItemController::class)
    ->middleware('auth')
    ->only(['index', 'show', 'store', 'destroy', 'update']);

Route::resource('/inventory', InventoryController::class)
    ->middleware('auth')
    ->only(['index', 'create', 'store', 'destroy', 'edit', 'update']);

Route::resource('/report', ReportController::class)
    ->middleware('auth')
    ->only(['index']);

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/layouts/components/footer.blade.php
			<footer class="mt-auto py-3 text-center">
{{--				<div class="container">--}}
{{--				--}}
{{--				</div>--}}
			</footer>

resources/views/layouts/components/main-header.blade.php
<header class="app-header">

    <!-- Start::main-header-container -->
    <div class="main-header-container container-fluid">

        <!-- Start::header-content-left -->
        <div class="header-content-left">
            <!-- Start::header-element -->
            <div class="header-element">
                <!-- Start::header-link -->
                <div>
                    <a class="sidebar-toggle sidemenu-toggle header-link" data-bs-toggle="sidebar" href="javascript:void(0);">
                        <span class="sr-only">Toggle Navigation</span>
                        <i class="ri-arrow-right-circle-line header-icon"></i>
                    </a>
                </div>
                <a aria-label="Hide Sidebar" class="sidemenu-toggle header-link animated-arrow hor-toggle horizontal-navtoggle" data-bs-toggle="sidebar" href="javascript:void(0);"><span></span></a>
                <!-- End::header-link -->
            </div>
            <!-- End::header-element -->
        </div>
        <div class="header-content-right">
            @auth
                <form method="POST" action="{{ route('logout') }}">
                    @csrf
                    <a href="{{route('logout')}}" onclick="event.preventDefault();this.closest('form').submit();">{{ __('Log Out') }}</a>
                </form>
            @else
                <a href="{{route('login')}}">{{ __('Login') }}</a>
            @endauth
        </div>
        <!-- End::header-content-left -->
    </div>
    <!-- End::main-header-container -->
</header>

resources/views/layouts/components/main-sidebar.blade.php
<aside class="app-sidebar" id="sidebar">


    <!-- Start::main-sidebar -->
    <div class="main-sidebar " id="sidebar-scroll">

        <!-- Start::nav -->
        <nav class="main-menu-container nav nav-pills flex-column sub-open">
            <div class="slide-left" id="slide-left"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24"
                                                         height="24" viewBox="0 0 24 24">
                    <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z"></path>
                </svg>
            </div>
            <ul class="main-menu">
                <!-- Start::slide__category -->
                <li class="slide__category"><span class="category-name">Main</span></li>
                <!-- End::slide__category -->

                <!-- Start::slide -->
                <li class="slide">
                    <a href="{{route('item.index')}}" class="side-menu__item">
                        <i class="ri-home-8-line side-menu__icon"></i>
                        <span class="side-menu__label">Items</span>
                    </a>
                </li>
                <li class="slide">
                    <a href="{{route('inventory.index')}}" class="side-menu__item">
                        <i class="ri-home-8-line side-menu__icon"></i>
                        <span class="side-menu__label">Inventory</span>
                    </a>
                </li>
                <li class="slide">
                    <a href="{{route('category.index')}}" class="side-menu__item">
                        <i class="side-menu__icon ti ti-apps"></i>
                        <span class="side-menu__label">Category</span>
                    </a>
                </li>
                <li class="slide">
                    <a href="{{route('tag.index')}}" class="side-menu__item">
                        <i class="ri-bubble-chart-line side-menu__icon"></i>
                        <span class="side-menu__label">Tags</span>
                    </a>
                </li>
                <!-- End::slide -->

                <!-- Start::slide__category -->
                <li class="slide__category"><span class="category-name">Reports</span></li>
                <!-- End::slide__category -->

                <!-- Start::slide -->
                <li class="slide">
                    <a href="{{route('report.index')}}" class="side-menu__item">
                        <i class="ri-bar-chart-fill side-menu__icon"></i>
                        <span class="side-menu__label">Weekly</span>
                    </a>
                </li>
                <!-- End::slide -->
            </ul>
            <div class="slide-right" id="slide-right"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24"
                                                           height="24" viewBox="0 0 24 24">
                    <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z"></path>
                </svg>
            </div>
        </nav>
        <!-- End::nav -->

    </div>
    <!-- End::main-sidebar -->

</aside>

resources/views/layouts/components/modal.blade.php
			<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModal" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-body">
							<div class="input-group">
								<a href="javascript:void(0);" class="input-group-text border-0 bg-transparent" id="Search-Grid"><i class="ri ri-search-2-line header-link-icon fs-14"></i></a>
								<input type="search" class="form-control form-control-sm border-0 px-2" placeholder="Search" aria-label="Username">
								<a href="javascript:void(0);" class="input-group-text border-0 bg-transparent" id="voice-search"><i class="ri ri-mic-2-line  header-link-icon"></i></a>
								<a href="javascript:void(0);" class="btn btn-light btn-icon border-0 bg-transparent" data-bs-toggle="dropdown" aria-expanded="false">
									<i class="ri ri-more-2-line"></i>
								</a>
								<ul class="dropdown-menu">
									<li><a class="dropdown-item" href="javascript:void(0);">Action</a></li>
									<li><a class="dropdown-item" href="javascript:void(0);">Another action</a></li>
									<li><a class="dropdown-item" href="javascript:void(0);">Something else here</a></li>
									<li><hr class="dropdown-divider"></li>
									<li><a class="dropdown-item" href="javascript:void(0);">Separated link</a></li>
								</ul>
							</div>
							<div class="mt-4">
								<p class="fw-semibold text-muted mb-2">Are You Looking For...</p>
								<span class="search-tags"><i class="ri ri-user-line me-2"></i>Team<a href="javascript:void(0)" class="tag-addon bg-transparent header-remove-btn"><i class="fe fe-x"></i></a></span>
								<span class="search-tags"><i class="ri ri-file-text-line me-2"></i>Forms<a href="javascript:void(0)" class="tag-addon bg-transparent header-remove-btn"><i class="fe fe-x"></i></a></span>
								<span class="search-tags"><i class="ri ri-map-pin-line me-2"></i>Maps<a href="javascript:void(0)" class="tag-addon bg-transparent header-remove-btn"><i class="fe fe-x"></i></a></span>
								<span class="search-tags"><i class="ri ri-server-line me-2"></i>Widgets<a href="javascript:void(0)" class="tag-addon bg-transparent header-remove-btn"><i class="fe fe-x"></i></a></span>
							</div>
							<div class="my-4">
								<p class="fw-semibold text-muted mb-2">Recent Search :</p>
								<div class="p-2 border br-5 d-flex align-items-center text-muted mb-2 alert">
									<a href="javascript:void(0);"><span>Notifications</span></a>
									<a class="ms-auto lh-1" href="javascript:void(0);" data-bs-dismiss="alert" aria-label="Close"><i class="fe fe-x text-muted"></i></a>
								</div>
								<div class="p-2 border br-5 d-flex align-items-center text-muted mb-2 alert">
									<a href="javascript:void(0);"><span>Alerts</span></a>
									<a class="ms-auto lh-1" href="javascript:void(0);" data-bs-dismiss="alert" aria-label="Close"><i class="fe fe-x text-muted"></i></a>
								</div>
								<div class="p-2 border br-5 d-flex align-items-center text-muted mb-0 alert">
									<a href="javascript:void(0);"><span>Mail</span></a>
									<a class="ms-auto lh-1" href="javascript:void(0);" data-bs-dismiss="alert" aria-label="Close"><i class="fe fe-x text-muted"></i></a>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<div class="btn-group ms-auto">
								<button class="btn btn-sm btn-primary-light">Search</button>
								<button class="btn btn-sm btn-primary">Clear Recents</button>
							</div>
						</div>
					</div>
				</div>
			</div>

resources/views/layouts/components/scripts.blade.php
         <!-- Scroll To Top -->
         <div class="scrollToTop">
            <span class="arrow"><i class="ri-arrow-up-s-fill fs-20"></i></span>
         </div>
         <div id="responsive-overlay"></div>
         <!-- Scroll To Top -->

         <!-- Popper JS -->
         <script src="{{asset('build/assets/libs/@popperjs/core/umd/popper.min.js')}}"></script>

         <!-- Bootstrap JS -->
         <script src="{{asset('build/assets/libs/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

         <!-- Node Waves JS-->
         <script src="{{asset('build/assets/libs/node-waves/waves.min.js')}}"></script>

         <!-- Simplebar JS -->
         <script src="{{asset('build/assets/libs/simplebar/simplebar.min.js')}}"></script>
         @vite('resources/assets/js/simplebar.js')

         <!-- Color Picker JS -->
         <script src="{{asset('build/assets/libs/@simonwep/pickr/pickr.es5.min.js')}}"></script>

         @yield('scripts')


         <!-- SS Custom JS -->
         <script src="{{asset('build/js/custom.js')}}"></script>

resources/views/layouts/components/styles.blade.php
        <!-- Choices JS -->
        <script src="{{asset('build/assets/libs/choices.js/public/assets/scripts/choices.min.js')}}"></script>

        <!-- Bootstrap Css -->
        <link id="style" href="{{asset('build/assets/libs/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" >

        <!-- Node Waves Css -->
        <link href="{{asset('build/assets/libs/node-waves/waves.min.css')}}" rel="stylesheet" > 

        <!-- Simplebar Css -->
        <link href="{{asset('build/assets/libs/simplebar/simplebar.min.css')}}" rel="stylesheet" >

        <!-- Color Picker Css -->
        <link rel="stylesheet" href="{{asset('build/assets/libs/flatpickr/flatpickr.min.css')}}">
        <link rel="stylesheet" href="{{asset('build/assets/libs/@simonwep/pickr/themes/nano.min.css')}}">

        <!-- Choices Css -->
        <link rel="stylesheet" href="{{asset('build/assets/libs/choices.js/public/assets/styles/choices.min.css')}}">